runtime: python
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

resources:
  cpu: 4
  memory_gb: 16
  disk_size_gb: 50

runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "3.11"

entrypoint: streamlit run Hello.py --server.port $PORT
