# Constants
# STREAMLIT VERSION

import streamlit as st

ELEVENLABS_API_KEY = st.secrets["ELEVENLABS_API_KEY"]
LANGCHAIN_API_KEY = st.secrets["LANGCHAIN_API_KEY"]
ANTHROPIC_API_KEY = st.secrets["ANTHROPIC_API_KEY"]
OPENAI_API_KEY = st.secrets["OPENAI_API_KEY"]

GOOGLE_JSON = st.secrets["GOOGLE_JSON"]

REUTERS_CLIENT_ID = st.secrets["REUTERS_CLIENT_ID"]
REUTERS_CLIENT_SECRET = st.secrets["REUTERS_CLIENT_SECRET"]